// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRkwX_3Ifw2k3WhUyIjYdRonuBQCxJnTg',
    appId: '1:392855434462:web:b9d3f779fee8ac2a23be4f',
    messagingSenderId: '392855434462',
    projectId: 'vibe-a0b9d',
    authDomain: 'vibe-a0b9d.firebaseapp.com',
    storageBucket: 'vibe-a0b9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8rQk_kG3cFnqKkm0s-mk_9EVYuXwAwR8',
    appId: '1:392855434462:android:45f0a4a3e20a393e23be4f',
    messagingSenderId: '392855434462',
    projectId: 'vibe-a0b9d',
    storageBucket: 'vibe-a0b9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGMzyITuj3JRskINeBdrzcyn4yqMlSHF8',
    appId: '1:392855434462:ios:e384b35ec961e3b023be4f',
    messagingSenderId: '392855434462',
    projectId: 'vibe-a0b9d',
    storageBucket: 'vibe-a0b9d.firebasestorage.app',
    iosBundleId: 'com.example.vibe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGMzyITuj3JRskINeBdrzcyn4yqMlSHF8',
    appId: '1:392855434462:ios:e384b35ec961e3b023be4f',
    messagingSenderId: '392855434462',
    projectId: 'vibe-a0b9d',
    storageBucket: 'vibe-a0b9d.firebasestorage.app',
    iosBundleId: 'com.example.vibe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRkwX_3Ifw2k3WhUyIjYdRonuBQCxJnTg',
    appId: '1:392855434462:web:7fc9a8ef7797002623be4f',
    messagingSenderId: '392855434462',
    projectId: 'vibe-a0b9d',
    authDomain: 'vibe-a0b9d.firebaseapp.com',
    storageBucket: 'vibe-a0b9d.firebasestorage.app',
  );
}
